### ISSUE TITLE
Family side effect

### ISSUE THREAD

**Issue by GregoryConrad** [GregoryConrad/rearch-dart#221]
Useful for dynamic programming, incremental computation, recursive capsules, and weird one offs.

Will need to make capsules dispose properly and also a use.forceAutoDispose (or the like)

**Comment by TekExplorer** [comment]
Ref: riverpod families

**Comment by GregoryConrad** [comment]
Thinking an API something like:

```dart
Family<Foo, Bar> fooBarFamily(CapsuleHandle use) {
  return use.family((use, Foo foo) {
    final client = use(httpClientCapsule);
    return Bar(client, foo);
  });
}

@rearchWidget
Widget example(WidgetHandle use, Foo foo) {
  // The below syntax requires some fun trickery, see next code snippet for impl
  final Bar bar = use(fooBarFamily[foo]);
  return BarWidget(bar: bar);
}
```

To support the `use(fooBarFamily[foo])` syntax, we can do a cool:

```dart
extension FamilyAccess<Param, Return> on Capsule<Family<Param, Return>> {
  Capsule<Return> operator [](Param p) => (CapsuleHandle use) => use(use(this)[p]);
}
```

**Comment by busslina** [comment]
Can you explain this side effect? The Riverpod one refers to identified instances of a kind (type), but here having two generic types confuses me.

Also, does the callback passed to `use.family` executes synchronously?

**Comment by busslina** [comment]
> Can you explain this side effect? The Riverpod one refers to identified instances of a kind (type), but here having two generic types confuses me.

I think I understod... `Foo` is the key.

**Comment by GregoryConrad** [comment]
It is akin to Riverpod families for really specific scenarios, or for odd one offs that can't be solved effectively with factories.

Not sure I'll call the resulting solution "family", since it's not too intuitive unless you're coming from Riverpod, but that's the placeholder name for now.

> Also, does the callback passed to use.family executes synchronously?

The family side effect will essentially just create capsules for each parameter passed in (think a `Map<Param, Capsule>`). That callback will provide the body of each newly created capsule.

> Can you explain this side effect?

In the possible API i gave above, `Foo` is the family key; `Bar` is the return value.

**Comment by GregoryConrad** [comment]
In the current experimental implementation, _dynamic capsules_ (I'm calling "families" that to be consistent with the Rust implementation/docs) would keep all of the keys/variants stored in the `Map` even when the data of the dynamic capsules themselves are destroyed. I'm not really sure this even constitutes as a problem, but if it were to be "fixed," one of the following would need to happen:

```dart
abstract interface class SideEffectApi {
  void forceIdempotent(); // new method that tells ReArch to disregard this particular side effect registration
}
```

```dart
abstract interface class SideEffectRegistrar {
  // register(), as before
  /// Is called whenever this capsule changes, whether that means it is rebuilt or disposed.
  /// Can be used to cleanup a resource.
  void cleanup(void Function()); // this f
}
```

Or maybe something similar. Not sure what I like more at the moment.

**Comment by GregoryConrad** [comment]
May also add some helper functions to `experimental.dart` to make stuff more ergonomic:

```dart
final myCapsule = capsule((use) {
  return use.data(123);
});

final myFamily = dynamicCapsule((use, Param param) {
  return use.data(param);
});
```

Not entirely sold on them since they:
1. lack type information in source code
2. are not `const`, but rather `final` since closures can't be `const` yet

But I think this would make since to include and users can opt-in when they want.

**Comment by GregoryConrad** [comment]
For those following, here's a test case that shows how to use this new (experimental) side effect:
```dart
  test('fibonacci numbers', () {
    DynamicCapsule<int, BigInt> fibonacciCapsule(CapsuleHandle use) {
      return use.dynamic((use, n) {
        return switch (n) {
          _ when n < 0 => throw ArgumentError.value(n),
          0 => BigInt.zero,
          1 => BigInt.one,
          _ => use(fibonacciCapsule[n - 1]) + use(fibonacciCapsule[n - 2]),
        };
      });
    }

    final container = useContainer();
    expect(
      container.read(fibonacciCapsule[100]).toString(),
      equals('354224848179261915075'),
    );
  });
```
I'll publish a new release shortly with the first iteration of the side effect, but keep in mind things may leak/not work perfectly for the time being.

**Comment by GregoryConrad** [comment]
New version released (1.12.0) with _experimental_ dynamic capsule implementation. It seems to work, but I wouldn't recommend using it for anything mission-critical anytime soon.

**Comment by TekExplorer** [comment]
> `dynamicCapsule`

Okay, but hear me out: `capsule.dynamic((use, arg) => ...)`

**Comment by GregoryConrad** [comment]
I've thought about this some more and decided on a few things:

- `forceIdempotent`, as mentioned [here](https://github.com/GregoryConrad/rearch-dart/issues/221#issuecomment-2380392779), is not going to happen. It clashes far too much with the rest of ReArch's design.
- I could add a `cleanup` style method on `SideEffectRegistrar`. The issue is that I never marked it `@experimental`, so it's possible someone using the library in some _really weird_ way could break. That might, however, be a risk worth taking.
  - Instead of `cleanup` on the `SideEffectRegistrar`, I could instead add it on `SideEffectApi`, but that would present numerous other problems. So that won't likely happen either.
- I vetted all the code again today (didn't take that long since the entire core implementation is only a few hundred lines of code--one selling point of ReArch 😄) and realized there wouldn't be any problems regarding dynamic capsules--everything is properly handled as-is. The only things is that `onNextUpdate` with dynamic capsules may be a bit leaky unless we:
  - (1) Trigger idempotent garbage collection a few levels deeper (say 5 or so), or
  - (2) Trigger idempotent garbage collection all the way until the "root" nodes of any branches used to build the leaf
  - (I'd probably just go with the first option to save implementation time & complexity, and do less at runtime)
- I think I'd want to rename some of the types:
  - `typedef DynamicCapsule<Param, Return> = Capsule<DynamicOrchestrator<Param, Return>>;`, or something like that.
  - This way we can refer to dynamic capsules as `DynamicCapsule`s directly.
  - And users won't try to treat dynamic capsules as regular capsules, because even though they are, they are a bit useless as such and require that special `[]` syntax to read out of them
- I do like `capsule.dynamic((use, arg) => ...)`, but I'm not entirely sold on it yet
  - Mostly because `capsule()` would mean `capsule` would be a top-level variable with a call, which would hurt the IDE experience just a little bit. Alas, here's some code you can use in your own project, since `capsule` and `dynamicCapsule` are still experimental anyways:
```dart
class _CapsuleCreationImpl {
  const _CapsuleCreationImpl();
  Capsule<T> call<T>(Capsule<T> cap) => cap;
  Capsule<DynamicCapsule<Param, Return>> dynamic<Param, Return>(
    Return Function(CapsuleHandle, Param) dyn,
  ) =>
      dynamicCapsule(dyn);
}

const capsule = _CapsuleCreationImpl();

// Usage:
final cap = capsule((use) => 123);
final cap2 = capsule.dynamic((use, int i) => '$i');
```

**Comment by GregoryConrad** [comment]
# TODOs
So I don't forget:
- [ ] (MAYBE) `SideEffectRegistrar.cleanup`, which would be used to cleanup resources without causing non-idempotence.
  - [ ] Could be used by the dynamic capsules side effect to remove capsules from the underlying `DynamicOrchestrator`'s map when they are disposed.
- [ ] Provide enhanced idempotent GC to `onNextUpdate` to prevent any leaky behavior when dynamic capsules are read from widgets.

**Comment by pishguy** [comment]
Regarding dynamic capsules, instead of a general cleanup on `SideEffectRegistrar`, I suggest considering an `onDispose` callback for each instance of a dynamic capsule. This approach is more specific, and also aligns better with the imperative and idempotent aspects of `ReArch`. Additionally, it allows managing resources like `StreamController` or Timer that need to be closed exactly when that specific capsule is disposed.

**Comment by busslina** [comment]
But, what happen with dependent capsules on dispose? What value they receive? I was just thinking they can receive a custom exception...

**Comment by busslina** [comment]
What I'm thinking (and implementing):

There will be two disposal types: automatic disposal and manual disposal.

Automatic disposal will happen automatically. The framework already does it. It dispose a capsule when it has no dependents and when it is idempotent (idempotent means it has no registered side effects, but it can have dependencies).

Manual disposal: Its quite opposite in some way. We must allow only disposal when the dynamic capsule has not dependents. It can have side effects registered and we must clean them. It must prevent disposal if it has any dependents (could be just a return false or throwing an error). The manual disposal can be triggered from within the dynamic capsule or from outside.

**Comment by busslina** [comment]
Implemented here: https://github.com/GregoryConrad/rearch-dart/pull/334

Also in my [fork](https://github.com/busslina/rearch-dart/commit/111c73e7279e53b1079256e25f92ce0634c30057) I exposed `SideEffectApi.disposer` which is a related feature

**Comment by busslina** [comment]
@pishguy 
>  I suggest considering an onDispose callback for each instance of a dynamic capsule.

You already can use `SideEffectApi.registerDispose` or `use.effect` with `const []`. Also on my PR there is `DynamicOrchestrator._onDispose` for any (manual and automatic) disposal.

**Comment by busslina** [comment]
Can't sleep. Thininking about dynamic capsules. We not riverpod...

**Comment by busslina** [comment]
Not autodispose. Not disposable. We just can use them and make them resource lightweight friendly.

**Comment by busslina** [comment]
Plus they dont match very well with the factory model. Lets say we have factory capsule receiving a string id. We cannot use that id for reading a dynamic capsule directly, because we are not in the building phase. We must store that id in reactive data and then on rebuild read the related dynamic capsule.

**Comment by busslina** [comment]
So... it is a real limitation to not be able to read outside building phase? Or it is justified to read outside it in some scenarios?

**Comment by GregoryConrad** [comment]
You’re likely not using dynamic capsules correctly—they are only meant for a few niche scenarios you are unlikely to encounter in the day-to-day in a Flutter application

**Comment by busslina** [comment]
I was just thinking. I only use them on around 10 places in all my code base. Most of them, if not all, on the backend.

But there are scenarios where could be use factories or dynamic capsules. And using factories could mean much more boilerplate.

For example, disks/raids manager. We want to have attached to each disk different functionalities like auto mount or state change notification. We could monitor individual state changes with the factory model, but is much more work. We have to track every disk state in a map, update the map, diff the map, ... If use there dynamic capsules we reduce complexity by tracking each state individually.

The case I mentioned mixin factories and dynamic capsules was just a thinking.

I would use much more dynamic capsules but I fear memory leaks. On the other hand I thinlk I already managed well a past memory leak issue.

Don't you consider this a good case for using dynamic capsules @GregoryConrad ?

**Comment by busslina** [comment]
Another possible case I just think of:

Now, in the backend I store websocket connections in maps (IMap). For any related data I create a new IMap.

- Box<IMap<String, WebsocketConnection>> websocketConnectionsCapsule
- Box<IMap<String, int>> _websocketConnectionMessageIdsCapsule
- Box<IMap<String, StreamSubscription>> _websocketConnectionSubscriptionsCapsule
- Box<IMap<String, _WebsocketConnectionState>> _connectionStatesCapsule

I will consider migrate this design to dynamic capsules so I can hide complexity. Migration would end probably with the same amount of different dynamic capsules, but the logic between them would dramatically simplify.

I must take care of releasing resources when the connection dies (no reconnection mode, always a new connection).

**Comment by GregoryConrad** [comment]
In this case it may make sense to just do one capsule with the string as a key and then a new composed type as the value and then grab what you need out of it (via a factory/cache). Dynamic capsules aren’t really designed to be used for any sort of resources. Can create a side effect that manages a store/cache of some resources and have a factory that references that cache to pull the values out, and then you can wire in cleanup of the items from the map to the disposal of the resource itself.

**Comment by busslina** [comment]
I understand the point. Is a fight/tension between two visions. Here you care about resources and cleanup. I care here about individual observability: Refactor some data maps into dynamic capsules allows us to have a better observability/reactivity to individual states. The down side is that dynamic capsules remain for ever so I have to try to cleanup the maximum I can every dynamic capsule resource when it is no longer needed. And we will have some undeletable data (associated to every side effect).

1º I think this is the way.
2º We have to clean/define better this way.
3º It is the ReArch big issue.

I coded my way to have disposable dynamic capsules but I'm not happy with it and I'm not using it. I used your experimental code base for it. On my next attempt, if there is one, I will try from scratch.

:)

**Comment by busslina** [comment]
Ephemeral capsules: https://github.com/GregoryConrad/rearch-dart/discussions/338 https://github.com/GregoryConrad/rearch-dart/pull/339

**Comment by busslina** [comment]
My fork: https://github.com/busslina/rearch-dart/tree/busslina
